# MQTT configuration to the broker
# Copy and modify this file to mqtt_config.yaml

# URL to the MQTT broker like: mqtt://localhost:1883
url: mqtt://localhost:1883

# User name for authentication
username: mqtt_broker_user

# Password for authentication
password: mqtt_broker_password

# QOS (quality of service) to use
qos: 0

topic: sdm72